name: Default (push)

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'

defaults:
  run:
    shell: bash

env:
  DOCKSAL_VERSION: develop
  # Setting these while testing locally may result in data loss, so only use in CI.
  PROJECT_INACTIVITY_TIMEOUT: 30s
  PROJECT_DANGLING_TIMEOUT: 60s
  DOCKSAL_DNS_DISABLED: 1
  DOCKSAL_DNS_DOMAIN: docksal.site
  EVENT_NAME: '${{ github.event_name }}'

jobs:
  default:
    name: 'Build, test, and push'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      -
        name: Source name
        id: source_name
        run: |
          echo "::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}"
          echo "::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}"
          if [[ ${{ github.event.ref }} =~ ^refs/tags/ ]]; then
              echo "::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}"
          else
              echo "::set-output name=SOURCE_TAG::"
          fi
      -
        name: Install BATS (tests)
        run: |
          git clone https://github.com/bats-core/bats-core.git
          cd bats-core
          sudo ./install.sh /usr/local
          bats -v
      -
        name: Install Docksal
        run: curl -sSL http://get.docksal.io | bash
      -
        name: fin version
        run: fin version
      -
        name: fin sysinfo
        run: fin sysinfo
      -
        # Pull curl image with http2 support (used in tests)
        name: Pull curl with http2 support
        run: docker pull badouralix/curl-http2
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build and test
        run: |
          make
          make start
          make exec -e CMD="env"  # Views env variables picked up by proxy
          make test
      -
        name: Release on success
        if: |
          success() &&
          (
            github.ref == 'refs/heads/develop' ||
            github.ref == 'refs/heads/master' ||
            startsWith(github.ref, 'refs/tags')
          )
        run: make release
        env:
          SOURCE_NAME: '${{ steps.source_name.outputs.SOURCE_NAME }}'
          SOURCE_BRANCH: '${{ steps.source_name.outputs.SOURCE_BRANCH }}'
          SOURCE_TAG: '${{ steps.source_name.outputs.SOURCE_TAG }}'
      -
        name: Log on failure
        if: ${{ failure() }}
        run: make logs
